db.test.insert({"key":"value1","key2":"Val2","key3":"val3"})
db.test.insert({"key":"value2","key2":"Val21","key3":"val31"})
db.test.insert({"key":"value3","key2":"Val22","key3":"val33"})
db.test.find()
db.test.find().pretty()
